#!/bin/bash

_lock() {

    until xidlehook --not-when-audio --not-when-fullscreen --timer 1500 "betterlockscreen --lock blur" "" --socket "/tmp/xidlehook.sock" ; do
    #echo "Xidlehook crashed with exit code $?.  Respawning.." >&2
    #notify-send -t 2000 "Xidlehook crashed" "Respawning..."
    sleep 1
    done

}

_start() {
    running="$(pgrep xidlehook)"
    if [[ -z $running ]]; then
        printf "Enabling autolock\n"
#         notify-send -t 2000 "Enabling autolock"
        _lock &
    else
        printf "Autolock.sh already running \n"
        notify-send -t 2000 "Autolock.sh already running"
    fi
}

_pause(){
    notify-send -t 2000 "Caffeinate" "Pausing lock and suspend"
    caffeinate &
}

_help(){
    cat <<- EOF
Usage: autolock [option]

Options:
    -h, help        show this message
    -e, enable      enable autolock and suspend
    -d, disable     disable autolock and suspend
    -p, pause       pause autolock and suspend
    -u, unpause     unpause caffeinate and enable lock and suspend

EOF
}

opt="${1:-"enable"}"

case "$opt" in
-h|help)
    _help
    ;;
-e|enable)
    _start
    ;;
-d|disable)
    printf  "Disabling autolock \n"
    notify-send -t 2000 "Disabling autolock"
    killall autolock && killall xidlehook
    ;;
-p|pause)
    _pause
    ;;
-u|unpause)
    notify-send -t 2000 "Reenabling autolock"
    killall caffeinate
    ;;
*)
    _help
esac
