#!/bin/bash

push(){
    echo push
}

pop(){
    echo pop
}

rofi_help(){
    awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc{,.common} |
    column -t -s $'\t' |
    rofi -dmenu -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40
}

hide(){
    bspc node -g hidden
}

unhide(){
    bspc node $(bspc query -N -n .hidden | tail -n1) -g hidden=off
}

receptacle(){
    receptacle=$(bspc query -N -n ".leaf.!window.local" | awk NR==1)
    bspc node -n "$receptacle"

}

equal(){
    bspc node @/ --equalize
}

help(){
    cat <<- EOF

Usage: bspscripts [function]

Functions:
    help        show this message
    hide        hide current node
    equal       equalize all nodes in tree
    unhide      unhide hidden nodes in order hidden
    receptacle  swap current node with receptacle space

EOF
}

"${1:-help}" "${*:2}"
