#!/bin/bash

file="$1"

if [[ ! -e "$file" ]]; then
    touch "$file"
fi

if [[ -t 0 ]]; then
    if [[ -z "$file" ]]; then
        nvim -o $*
    elif [[ -w "$file" ]]; then
       nvim -o $*
    elif [[ ! -w "$file" ]]; then
        sudo nvim $*
    fi
else
    if [[ -z "$file" ]]; then
        $TERMINAL -e "nvim -o $*"
    elif [[ -w "$file" ]]; then
        $TERMINAL -e "nvim -o $*"
    elif [[ ! -w "$file" ]]; then
        $TERMINAL -e "sudo nvim $*"
    fi
fi
