#!/usr/bin/env bash


while sleep 1; do
    for i in {1..5}; do
        temp[i]=$(nvidia-settings -q gpucoretemp -t | awk NR==1)
        sleep 2
    done

    sum=0; total=0
    for i in "${temp[@]}"
    do
        ((sum += $i))
        ((total++))
    done
    avg=$((sum/total))
    echo "temp:" $avg

    if (($avg < 55 )); then
        speed=25
    elif (($avg >= 55 && $avg <= 65)); then
        speed=30
    elif (($avg >= 65 && $avg <= 72)); then
        speed=35
    elif (($avg >= 72 && $avg <= 80)); then
        speed=40
    elif (($avg >= 80)); then
        speed=50
    fi
    #echo "speed:" $speed

    2>/dev/null 1>&2 nvidia-settings -a [gpu:0]/GPUFanControlState=1 -a [fan-0]/GPUTargetFanSpeed="$speed"

done
