#! /usr/bin/env bash
# opi scripts

rofi_dmenu='rofi -i -dmenu -lines 8 -width 40 -padding 20 -format q -multi-select'

_opiOpen(){
    dir="${*:-"/home/rob/"}"
    fd . $dir -H -t f -i | $rofi_dmenu -p "Open" | xargs -L 1 -r xdg-open

}

_opiDir(){
    dir="${*:-"/home/rob/"}"
    file=$( fd . $dir -H -a -t d -t l | $rofi_dmenu -p "Dir")
    [[ -z $file ]] || $TERMINAL -e "vifm $file"
}

_opiEdit(){
    dir="${*:-"/home/rob/"}"
    files="$( fd . $dir -H -t f -i | $rofi_dmenu -p "Edit" )"
    for file in $files; do
        /home/rob/.bin/nv $file &
    done
}

_opiAsk() {
    dir="$(rofi -p "Search" -dmenu)"
    file=$( fd . $dir -H -t f -i | $rofi_dmenu -p "Search" )
    [[ -z "$file" ]] && exit 0

    /home/rob/.bin/nv $file
}

_opiCopy(){
    dir="${*:-"/home/rob/"}"
    fd . $dir -H -a -t f -i | $rofi_dmenu -p "Copy" | xclip -selection c
}


_help() {
    cat <<- EOF
Usage: opi command [path]

Commands:
     -h, help      Display this message
     -a, ask       Ask which dir to search
     -c, copy      copy output
     -o, open      Open file
     -d, dir       Open dir
     -e, edit      Edit file

EOF
}

case "$1" in
    -h|help )
        _help
        exit 0
        ;;
    -a|ask )
        _opiAsk
        exit 0
        ;;
    -c|copy )
        if [[ -n $2 ]]; then
            _opiCopy "${*:2}"
        else
            _opiCopy
        fi
        ;;
    -o|open )
        if [[ -n $2 ]]; then
            _opiOpen "${*:2}"
        else
            _opiOpen
        fi
        ;;
    -d|dir )
        if [[ -n $2 ]]; then
            _opiDir "${*:2}"
        else
            _opiDir
        fi
        ;;
    -e|edit )
        if [[ -n $2 ]]; then
            _opiEdit "${*:2}"
        else
            _opiEdit
        fi
        ;;
    *) printf >&2 "Invalid option\n\n"; _help; exit 1;;
   esac
