#!/bin/bash

PS3='Please enter your choice: '
options=("nvim" "vifm" "zshrc" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "nvim")
            scp laptop:~/.config/nvim/init.vim ~/.config/nvim/init.vim
            ;;
        "vifm")
            scp laptop:~/.config/vifm/vifmrc ~/.config/vifm/vifmrc
            ;;
        "zshrc")
            scp laptop:~/.zshrc ~/.zshrc
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
