#!/bin/bash
set -e

_help() {
    cat <<- EOF
Usage: rname {files}


EOF
}

_rename(){
	tmpfile="$(find /tmp/rname.*)"
	if [[ -z $tmpfile ]]; then
		printf "temp file not found. exiting."
		exit 1
	fi

	$EDITOR $tmpfile

}

if [ ${#} -eq 0 ]; then
    if [ -p "/dev/stdin" ]; then
		cat /dev/stdin | tr ' ' '\n' >> "$(mktemp -t rname.XXXXX)"
		_rename
    else
		_help
		exit 0
    fi
else
    printf ${*} | tr ' ' '\n' >> "$(mktemp -t rname.XXXXX)"
fi

_rename

rm -rf /tmp/rname.*
