#!/usr/bin/env sh

func="${1:-"win"}"

win() {
	maim -B -u -b 3 -s | xclip -selection clipboard -t image/png && notify-send -t 2000 "Current Window Captured" "Copied to Clipboard"
}

screen() {
	maim -x $DISPLAY.0 -B -u -f png -m 10 ~/pics/scrots/"scrot_$(date +%F-%H-%M-%S)".png
}

$func
