#!/bin/bash


#mediainfo --Inform="General;File Name=%CompleteName%\nFile Size=%FileSize/String1%" "$@";

#mediainfo --Inform="Video;Resolution=%Width%x%Height%\nCodec=%CodecID%\nBitrate= %BitRate/String%" "$@";

#mediainfo --Inform="Video;Resolution=%Width%x%Height%\nCodec=%CodecID%\nBitrate= %BitRate/String%" "$@";

if [[ -d "$1" ]]; then
	vids="$(fd . "$1" -t f -e mp4 -e mkv)"
else
	vids="$*"
fi

for f in "$vids"; do
	#bitrate="$(mediainfo --Inform="Video;%OverallBitRate%" "$f")"
	mediainfo --Inform="General;%OverallBitRate% : %CompleteName%" "$f"
	mediainfo --Inform="Video;Resolution=%Width%x%Height%\nCodec=%CodecID%\nBitrate= %BitRate/String%" "$f";

done | sort -t ':' -nk1
