#!/usr/bin/env sh
# Terminate already running bar instances
killall -q compton

# Wait until the processes have been shut down
while pgrep -x compton >/dev/null; do sleep 0.25; done

compton -b --config /home/rob/.config/compton.conf &
