#!/bin/bash
. /home/rob/.profile
# Program functions

_picom(){
    picom --experimental-backends --backend glx -b --config /home/rob/.config/picom/picom.conf
}

_pbar(){
    /home/rob/.bin/pbar.sh
}

_dunst(){
	/usr/bin/dunst
}

_sxhkd(){
until sxhkd -s $HOME/.cache/sxhkd.fifo; do
    notify-send "sxhkd crashed with exit code $?.  Respawning.." >&2
    sleep 1
done

}

_polkit(){
	nullify /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
}

_obs(){
    nullify obs --profile Default --minimize-to-tray &

}

_dpms(){
	xset s 1215 1215

	xset dpms 1215 1215 1215
}

_pulse(){
	pulseaudio -k;pulseaudio --start
}


for i in $*; do
	pkill "$i"

	# Wait until the processes have been shut down
	while pgrep -x "$i" >/dev/null; do sleep 0.25; done

	2>/dev/null 1>&2 _$i &
done
