#!/usr/bin/env sh
# Terminate already running bar instances
killall -q picom

# Wait until the processes have been shut down
while pgrep -x picom >/dev/null; do sleep 0.25; done

picom --experimental-backends --backend glx -b --config /home/rob/.config/picom/picom.conf &
