#!/bin/bash
. /home/rob/.profile
# Program functions

_picom(){
	persist picom --experimental-backends
}

_pbar(){
    /home/rob/.bin/pbar.sh
}

_dunst(){
	/usr/bin/dunst
}

_sxhkd(){
	persist sxhkd -s $HOME/.cache/sxhkd.fifo
}

_nm-applet(){
	/usr/bin/nm-applet
}

_pia-client(){
	/opt/piavpn/bin/piactl background enable
	nullify /opt/piavpn/bin/pia-client --quiet

}

_polkit(){
	nullify /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
}

_obs(){
    nullify obs --profile Default --minimize-to-tray

}

_ssr(){
	nullify simplescreenrecorder --start-hidden --settingsfile=/home/rob/.ssr/fullscreen.conf
}

_dpms(){
	xset s 1215 1215

	xset dpms 1215 1215 1215
}

_pulse(){
	pulseaudio -k && pulseaudio --start
}


for i in $*; do
	pkill "$i"

	# Wait until the processes have been shut down
	while pgrep -x "$i" >/dev/null; do sleep 0.25; done

	_$i &
done
