#!/bin/bash
# backup_remote.sh
# rdiff-backup wrapper script

_backup(){
    sleep 3s
	/home/rob/.bin/rsync_backup.sh / root@192.168.2.21:/data/backups/rob-pc /home/rob/docs/backup_exclude.txt
}

_sleep(){
    sleep 2s && /home/rob/.bin/sethue && sudo systemctl suspend
}


time="$(date +%H%M)"

if [[ $time -gt 0550 && $time -lt 0630 ]]; then
    /usr/bin/hue power off
    _backup
    _sleep
else
    _backup
fi
