#!/bin/bash
# backup_remote.sh
# rdiff-backup wrapper script

_backup(){
    sleep 3s
    rdiff-backup --ssh-no-compression --exclude-globbing-filelist /home/rob/docs/backup_exclude.txt / bb::/data/backups/rob-pc/ && rdiff-backup --remove-older-than 90D bb::/data/backups/rob-pc/
}

_sleep(){
    sleep 2s && sudo -u rob /home/rob/.bin/hue.sh
    systemctl suspend
}


time="$(date +%k%M)"

if [[ $time -gt 550 && $time -lt 630 ]]; then
    sudo -u rob hue power off
    _backup
    _sleep
else
    _backup
fi
