#!/bin/bash

set -e


_setvars(){
	file="${@: -1}"
	newfile="$file-trim"
}

_fromTime(){
	ffmpeg -ss "$1" -t "$2" -i "$3" -vcodec copy -acodec copy "$newfile"
}

_fromStart(){
	ffmpeg -ss 0 -t "$1" -i "$2" -vcodec copy -acodec copy "$newfile"
}

_fromEnd(){
	ffmpeg -sseof 0 -t "$1" -i "$2" -vcodec copy -acodec copy "$newfile"
}

_help(){
	    cat <<- EOF
Usage: trimvid [opt] [(time)time] [file]

Options:
    -e, end			amount of time to clip from end
	-s, start		amount of time to clip from start
	-t, time		amount of time to clip from [time]
	-h. help		help message
EOF
}

[[ -f "${@: -1}" ]] && _setvars

case $1 in
    -e|end)
        _fromEnd "${*:2}"
        ;;
	-s|start)
		_fromStart "${*:2}"
		;;
	-t|time)
		_fromTime "${*:2}"
		;;
	-h|help)
		_help
		;;
	*)
		if [[ -f "${@: -1}" ]]; then
			_fromStart "$1"
		else
			_help
		fi
		;;
esac
