#!/bin/sh
bspc wm -O DVI-D-0 DP-0 HDMI-0

/home/rob/.bin/start sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9

bspc config remove_disabled_monitors true

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false

bspc config normal_border_color '#111111'
bspc config active_border_color '#111111'
bspc config focused_border_color '#eeeeee'
bspc config presel_feedback_color '#eeeeee'

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config automatic_scheme alternate

bspc rule -r *:*
bspc rule -a TelegramDesktop:telegram-desktop monitor=DP-0
bspc rule -a privateinternetaccess:pia-client state=pseudo_tiled

export QT_QPA_PLATFORMTHEME=gtk2

/home/rob/.config/bspwm/autostart.sh &
